language: node_js
node_js:
  - stable

install:
  - npm install -g gulp
  - npm install

script:
  - gulp validate

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master

env:
  global:
  - ENCRYPTION_LABEL: "2a77fe576461"
  - COMMIT_AUTHOR_EMAIL: "jonathan.bouzekri@gmail.com"
